# Name of workflow
name: check

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        # Step's name
        # Cache installed Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '8.4'
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint
      # - name: Create .env file
      #   run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
      - name: Run PHPUnit with code coverage
        # Run tests and generate coverage report
        run: make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # NOTE: https://sonarcloud.io/project/information?id=<organization>_<reponame>
          args: >
            -Dsonar.projectKey=maxheong54_php-project-9
            -Dsonar.organization=maxheong54
            -Dsonar.sources=src/
            -Dsonar.php.coverage.reportPaths=build/logs/clover.xml
